spring:
  profiles:
    include: security
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379

h2:
  console:
    enabled: true
    path: /h2-console

#spring:
#  redis:
#    host: localhost
#    port: 6379

